### ISSUE TITLE
Добавить ридми

### ISSUE THREAD

**Issue by puzanov** [DanielVartanov/newsdiff-on-blockchain#1]
Байке, нифига ведь непонятно. Распиши кратко функциональные возможности и архитектуру. Контрибютить хотим.

**Comment by puzanov** [comment]
@DanielVartanov, ну напиши ридмиху, ну чо ты.

**Comment by DanielVartanov** [comment]
Да напишу, мне тут работа отдых попортила чуть-чуть

**Comment by DanielVartanov** [comment]
Готовченко.
