### ISSUE TITLE
checking for pg_config... no

### ISSUE THREAD

**Issue by puzanov** [DanielVartanov/newsdiff-on-blockchain#2]
Можно ли убрать зависимость от Постгреса при начальном bundle install? Ставить ПГ для тестов на маке анриал.

**Comment by 2bj** [comment]
+1

![Alt text](https://monosnap.com/file/TlqNvGTgeCVxIh3QYstrsxjCVmADNk.png)

**Comment by DanielVartanov** [comment]
Ок, сделаем, он только для продакшина нужен, я разделю, спасибо за идею

**Comment by DanielVartanov** [comment]
Готово

**Comment by DanielVartanov** [comment]
Осторожно, много ломающих изменений! Всё просто на изнанку вывернуто в новых коммитах
