### ISSUE TITLE
Веб морда со всеми дифами 

### ISSUE THREAD

**Issue by puzanov** [DanielVartanov/newsdiff-on-blockchain#3]
Предлагаю помимо плагина, который покажет как изменялась новость, которую читаеешь, сделать веб-морду проекта, где показывать все дифы, которые можно апать. 

Получается будет два списка: hot & new, в горячих в топе будут в основном ржаки

Эта вебморда привлечет кучу народу и завирусится.

**Comment by DanielVartanov** [comment]
Изначально я думал, что полный список редактирований никто читать не будет -- это скучно, там одна ржака на 50 записей.

Но я тут поговорил со знающими, мне сказали, что если сделать фильтр по новостным агенствам, новостники буду жадно просматривать ляпы конкурентов :-) 

В общем, запилю вьюшку, пусть Эликсир это мордочку и раздаёт.

Спасибо за предложение :-)
